[package]
name = "egui_wgpu"
version = "0.1.0"
authors = ["clam-shell-clancy"]
edition = "2018"

[dependencies]
wgpu = "0.6"
egui = "0.1.3"
bytemuck = "1.4.1"

[dev-dependencies]
futures = "*"
winit = "*"
